### ISSUE TITLE
No route info for this topic

### ISSUE THREAD

**Issue by vitem** [ThierrySquirrel/rocketmq-spring-boot-starter#1]
想法非常好，但是报No route info for this topic 

我加了：@EnableRocketMQ
有没有需要注意的点

**Comment by vitem** [comment]
我用的是aliyun 提供的mq服务

**Comment by ThierrySquirrel** [comment]
1.需要在阿里云开通消息队列 RocketMQ
2.在管理控制台添加Topic与Group

**Comment by vitem** [comment]
您好，aliyun的mq线上一直在用，肯定是不会写错的，我看了一下，唯一不同的是我的springboot是2.0.9,由于各种原因，升级不了2.1.4,帮忙看下你的这个会不会在2.0.9下有问题

**Comment by ThierrySquirrel** [comment]
您好，看到回复后，测试了2.1.5版本与2.0.9版本的springboot 没有发现异常
使用前，请检查group与topic是否在阿里云控制台创建，且配置文件内容，配置正确

**Comment by vitem** [comment]
http://onsaddr.mq-internet-access.mq-internet.aliyuncs.com:80,
大家千万别把":80"删掉
坑

**Comment by ThierrySquirrel** [comment]
看来得到好的解决，没有其它错误的话，将在24小时内结束此问题。
