### ISSUE TITLE
默认的DefaultMessageListener实现BUG

### ISSUE THREAD

**Issue by pla423** [ThierrySquirrel/rocketmq-spring-boot-starter#11]
``` 
<dependency>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
            <groupId>com.github.thierrysquirrel</groupId>
            <version>2.0.6-RELEASE</version>
        </dependency>
```
如果用户只是想接收到字符串
![图片](https://user-images.githubusercontent.com/20533563/61373991-cfd33c00-a8cd-11e9-93ef-52be70e496d3.png)
那么如果消息中的如果带有“：” 则解析会直接抛出解析异常
可以在实现的时候判断下如果接收者要的就是String类型 那么可以不用做json转换

**Comment by ThierrySquirrel** [comment]
下个版本为配备自定义序列化操作,请耐心等待.
