### ISSUE TITLE
不用注解的方式怎么发送消息呢

### ISSUE THREAD

**Issue by heyzayz** [ThierrySquirrel/rocketmq-spring-boot-starter#12]
不用注解的方式怎么发送消息呢

**Comment by pla423** [comment]
代码你直接接入的话  可以去看阿里的文档  ons_clientAPI接入 ------------------ 原始邮件 ------------------
发件人: "heyzayz"<notifications@github.com>
发送时间: 2019年8月16日(星期五) 晚上7:36
收件人: "ThierrySquirrel/rocketmq-spring-boot-starter"<rocketmq-spring-boot-starter@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [ThierrySquirrel/rocketmq-spring-boot-starter] 不用注解的方式怎么发送消息呢 (#12)



不用注解的方式怎么发送消息呢
 
&mdash;

**Comment by lsw1990** [comment]
同问，定时那部分如果是根据业务动态设置时间怎么能？

**Comment by ThierrySquirrel** [comment]
您好,非注解发送消息,请采纳阿里云官方文档https://help.aliyun.com/document_detail/114448.html?spm=a2c4g.11186623.6.568.1c42d54c035djn

**Comment by ThierrySquirrel** [comment]
您好2.1.0-RELEASE版本支持动态时间,请使用注解@StartDeliverTime,当然,仍然建议您使用定时任务平台,或定时任务技术达到动态效果.

**Comment by ThierrySquirrel** [comment]
长时间的回复,再次深表歉意,同时非常感谢大家对此项目的支持.再次感谢大家.
