### ISSUE TITLE
Rocket

### ISSUE THREAD

**Issue by songzeyang** [ThierrySquirrel/rocketmq-spring-boot-starter#13]
如题

**Comment by songzeyang** [comment]
无

**Comment by pla423** [comment]
对



---原始邮件---
发件人: "songzeyang"<notifications@github.com&gt;
发送时间: 2019年9月6日(星期五) 中午1:56
收件人: "ThierrySquirrel/rocketmq-spring-boot-starter"<rocketmq-spring-boot-starter@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ThierrySquirrel/rocketmq-spring-boot-starter] 是否只可以使用阿里云RocketMQ？ (#13)



如题

**Comment by songzeyang** [comment]
Apache 也不可以对吧？

**Comment by pla423** [comment]
对



---Original---
