### ISSUE TITLE
每个线程创建一个客户端实例?不应该是共享一个实例？

### ISSUE THREAD

**Issue by lsw1990** [ThierrySquirrel/rocketmq-spring-boot-starter#14]
我看你的源码是创建了多个Producer在不同线程中，不应该是不同线程中同享同一个实例用？

**Comment by ThierrySquirrel** [comment]
您好,在此引用阿里云官网文档的话https://help.aliyun.com/document_detail/55385.html?spm=a2c4g.11186623.6.576.62d24f99OgCUji
创建的 Producer 和 Consumer 对象为线程安全的,可以在多线程间进行共享，避免每个线程创建一个实例

**Comment by ThierrySquirrel** [comment]
给您带来的不变深表歉意,在此感谢您的支持.再次感谢.
