### ISSUE TITLE
延迟队列消费失败

### ISSUE THREAD

**Issue by jackey-jiang** [ThierrySquirrel/rocketmq-spring-boot-starter#15]
![image](https://user-images.githubusercontent.com/10288803/74537086-5a6b3f00-4f74-11ea-8317-a3377e2efeeb.png)

如图所示,消费者代理失败！请问大佬 这是为何

**Comment by ThierrySquirrel** [comment]
您好,请检查生产者与消费者是否为同一序列化实现,建议自定义序列化排错。
1.消息生产与消费,框架内部有默认序列化实现,如使用其它方式投递,建议自定义序列化

**Comment by jackey-jiang** [comment]
重启jvm后 第一次 是ok的,后续的 就不行了,然后就一直进入重试 如图 消费者
![image](https://user-images.githubusercontent.com/10288803/74538132-85569280-4f76-11ea-9c49-dac8c9c2c804.png)
是否有配置错误呢

**Comment by ThierrySquirrel** [comment]
一直重试,是因为具有消息重新投递机制.
1.如果使用了非同一方式序列化投递,将会报错.
2.建议自定义序列化消费错误投递,或使用阿里云控制台进行操作.

**Comment by jackey-jiang** [comment]
这个是发送者:
![image](https://user-images.githubusercontent.com/10288803/74538821-f3e82000-4f77-11ea-9fe4-801c6c30aea8.png)
这个是消费者:
![image](https://user-images.githubusercontent.com/10288803/74538853-02363c00-4f78-11ea-9a21-08de141312bb.png)

疑惑的是从您这边抛出的这个异常 可能是因为哪些原因造成的呢:
![image](https://user-images.githubusercontent.com/10288803/74538909-18dc9300-4f78-11ea-9b05-38a39ca81a4a.png)

**Comment by jackey-jiang** [comment]
好的, 我试试

**Comment by ThierrySquirrel** [comment]
如果可以的话,建议您使用阿里云控制台,消费出现错误的消息.
