### ISSUE TITLE
多环境可以支持吗？

### ISSUE THREAD

**Issue by fanmuyong** [ThierrySquirrel/rocketmq-spring-boot-starter#17]
比如我的mq的topic，group每个环境都不一样，如果在注解中的代码里写死很麻烦吧

**Comment by zbjincheng** [comment]
注解可以用@RocketListener(groupID = "${mq.group}")这种获取配置的方式赋值。

**Comment by CoderLiuyang** [comment]
直接用你的 profile多环境启动

**Comment by CoderLiuyang** [comment]
可以写个全局类用多环境加载

**Comment by ThierrySquirrel** [comment]
给您带来的不便深表歉意.
有考虑过多环境支撑,group,topic环境隔离良好解决方案为:基于不同版本项目开发.这里推荐配合git
阿里云rocketmq主用于生产环境,静态group与topic也是良好的选择.
在此感谢您的支持.

**Comment by ThierrySquirrel** [comment]
没有其它问题的话,将在24小时内关闭提问.
