### ISSUE TITLE
支持阿里云http-sdk吗

### ISSUE THREAD

**Issue by WangzJi** [ThierrySquirrel/rocketmq-spring-boot-starter#19]
建议owner主页留一下邮箱，对这个项目很感兴趣

**Comment by ThierrySquirrel** [comment]
阿里云RocketmqHttp模块?很好的想法,Http提供多语言良好的支持.
近期处于生病状态,会休息一段时间.
感谢您的提议.

**Comment by WangzJi** [comment]
可以讨论一下集成http的方式吗

**Comment by ThierrySquirrel** [comment]
集成Http目前未做良好的调研,无法给出结论.
按照您的意见主页在24小时内保留邮箱.
如果有什么可以帮助您的地方,会加以支持.
感谢您对阿里云Rocketmq的关注.

**Comment by ThierrySquirrel** [comment]
没有其它问题的话,将在24小时内关闭提问.
