### ISSUE TITLE
没用阿里云的rocketemq可以使用这个jar吗

### ISSUE THREAD

**Issue by yangyz** [ThierrySquirrel/rocketmq-spring-boot-starter#21]
![image](https://user-images.githubusercontent.com/6257884/116538082-a4daa080-a919-11eb-9800-4dfa55e67625.png)
  上面上要求输入 阿里云的  accessKey SecretKey    没有这些能用吗 不是指定机器IP和端口吗

**Comment by ThierrySquirrel** [comment]
您好:
当前项目是引用商业版SDK进行开发.
社区版SDK与商业版SDK区别如下:
1.所有社区版的SDK均由Apache RocketMQ社区提供,您可获取源码自行编译,但不在阿里云RocketMQ的SLA范围.
2.和社区版SDK相比,商业版的SDK提供了更加丰富的功能特性并具有更高的稳定性保障,推荐您使用商业版SDK访问阿里云消息队列RocketMQ版.

**Comment by ThierrySquirrel** [comment]
没有其它问题的话,将在24小时内关闭提问.
