### ISSUE TITLE
引入后 启动项目时 报错

### ISSUE THREAD

**Issue by kickDick** [ThierrySquirrel/rocketmq-spring-boot-starter#23]
![image](https://user-images.githubusercontent.com/25758570/129132024-09f3189b-a23b-4a16-9334-75a0dfc9f1b4.png)

Error:(4, 45) java: 无法访问com.github.thierrysquirrel.annotation.EnableRocketMQ
  错误的类文件: /D:/repo/com/github/thierrysquirrel/rocketmq-spring-boot-autoconfigure/2.3.0.6-RELEASE/rocketmq-spring-boot-autoconfigure-2.3.0.6-RELEASE.jar!/com/github/thierrysquirrel/annotation/EnableRocketMQ.class
    类文件具有错误的版本 55.0, 应为 52.0
    请删除该文件或确保该文件位于正确的类路径子目录中。

**Comment by ThierrySquirrel** [comment]
您好:
  52.0版本对应Java8.0环境,55.0版本对应Java11环境.
  您可以升级Java11环境使用此项目,或者下载代码,重新编译,打包到自己本地的Maven仓库进行使用.

**Comment by ThierrySquirrel** [comment]
没有其它问题的话,将在24小时内关闭提问.

**Comment by ThierrySquirrel** [comment]
没有其它问题的话,将在24小时内关闭提问.
