### ISSUE TITLE
初始化订阅消费时，批量消费初始化完成后没有return吧？

### ISSUE THREAD

**Issue by marx828** [ThierrySquirrel/rocketmq-spring-boot-starter#24]
![image](https://user-images.githubusercontent.com/24307703/139569394-933f2c58-c874-48c6-8763-ae896beaae18.png)
感觉这块少一个return呢？为啥是不需要的呢？

**Comment by ThierrySquirrel** [comment]
您好:
感谢你对本项目的支持,bug已在2.3.1.0-RELEASE版本中修复.

**Comment by ThierrySquirrel** [comment]
没有其它问题的话,将在24小时内关闭提问.
