### ISSUE TITLE
分区顺序消息

### ISSUE THREAD

**Issue by marx828** [ThierrySquirrel/rocketmq-spring-boot-starter#25]
分区顺序消息应该是没支持吧，目前shardingkey在OrderMessage注解中只是一个值，应该达不到分区顺序消息的需求

**Comment by ThierrySquirrel** [comment]
您好:
感谢你对本项目的支持,在2.3.1.0-RELEASE版本中使用@ShardingKey达到分区顺序消息的需求

**Comment by ThierrySquirrel** [comment]
没有其它问题的话,将在24小时内关闭提问.
