### ISSUE TITLE
引入pom包下载不下来

### ISSUE THREAD

**Issue by 1226676454** [ThierrySquirrel/rocketmq-spring-boot-starter#26]

**Comment by ThierrySquirrel** [comment]
该项目遵循Apache2.0 License http://www.apache.org/licenses/
许可证是免费的.您可以下载代码,根据需要进行修改,并在自己的项目中使用它

**Comment by ThierrySquirrel** [comment]
没有其它问题的话,将在24小时内关闭提问.
