### ISSUE TITLE
自定义延时时间怎么设置

### ISSUE THREAD

**Issue by asasdasasd** [ThierrySquirrel/rocketmq-spring-boot-starter#3]
能自定义延时发送的延时时间么？

**Comment by ThierrySquirrel** [comment]
请使用@CommonMessage注解，设置topic与tag，startDeliverTime配合timeUnit设置多久后投递

**Comment by ThierrySquirrel** [comment]
没有其它问题的话，将在24小时内结束此提问。

**Comment by asasdasasd** [comment]
@ThierrySquirrel 能有个demo么，不是太明白怎么设置

**Comment by ThierrySquirrel** [comment]
这是中文地址： https://github.com/ThierrySquirrel/rocketmq-spring-boot-starter/blob/master/README_zh_CN.md

**Comment by asasdasasd** [comment]
不好意思，我的java不是太熟练，调用方法时怎么设置注解里面参数的值呢

**Comment by asasdasasd** [comment]
意思是延时时间不是固定的，需要动态设置

**Comment by ThierrySquirrel** [comment]
阿里云RocketMQ单一队列，百万消息，不用担心消息囤积问题，性能上承受了双十一的考验，也不必担心性能。延时和定时，就显得不是那么重要，且有太多可替代方案。
在阿里云官方例子中明确看出，定时消息，与延时消息，大同小异。
动态，建议使用定时任务工具
解决方案：
1.在指定的时间，调用发送消息接口
2.使用Springboot定时任务
3.使用其它定时任务框架，在指定时间调用发送消息接口

思路分析：
一大致上为两种，
1.在指定好的时间（如：晚上6点）调用发送消息接口，达到定时
2.定时任务，配合代码逻辑（检测此时间，是否需要发送消息），达到定时

**Comment by asasdasasd** [comment]
业务需要，发送时间确实是不固定，没办法定时啊，总不能每分钟都定时检查吧

**Comment by ThierrySquirrel** [comment]
可以配合Springboot 定时任务，来达到需求
