### ISSUE TITLE
TransactionMessage能否支持自定义LocalTransactionChecker？

### ISSUE THREAD

**Issue by wwjjkk** [ThierrySquirrel/rocketmq-spring-boot-starter#6]
PutProducerStrategy中指定使用DefaultLocalTransactionChecker，这个checker应该是需要自己根据各自的业务去自行扩展的吧。 另外TransactionMessage注解中transactionStatus属性也有点不理解，不应该是根据checker里的查询结果返回不同的status吗？

**Comment by ThierrySquirrel** [comment]
您好,DefaultLocalTransactionCheckert通过使用TransactionMessage注解进行控制
TransactionMessage中的注解transactionStatus指的是,事务触发回查机制后,进行的操作
这里的回查机制为,阿里云端,未能收到消息是否进行提交,或取消操作,进行回查.
简单理解为,投递消息出现错误,如超时操作时,进行的检查机制.
RocketMQ分布式事务采用最终一致性,其核心概念为:确保生产者消息能够投递,确保消费者能够消息消息.
在使用时建议使用默认即可.

**Comment by wwjjkk** [comment]
不对吧，按我的理解消息回查是为了确保生产者的本地事务执行成功后才能将mq中的“半消息”改为可发送的消息提供给消费者。按照目前您框架中默认的checker执行的话，相当于进行回查时没有任何依据的情况下默认本地事务一定成功并返回commit状态给mq了

**Comment by wwjjkk** [comment]
com.github.thierrysquirrel.core.producer包下的三个Default对象一般都需要根据系统自行扩展的才对，不知道目前是否支持扩展，如何操作

**Comment by ThierrySquirrel** [comment]
您好,在框架中,触发事务检查机制,要达到条件,还是比较苛刻的.
1.注解方法中代码全部执行完毕,从而进行消息投递.
2.消息投递期间不影响调用方代码执行.
3.在消息投递过程中,出现了断网,或重启等操作,消息则无法投递,触发回查
4.触发3的条件,很高概率调用方代码块,也无法正常执行
您如果非要保障强一致性,建议采用默认回滚,后续采取补偿机制.

**Comment by wwjjkk** [comment]
哎，感觉目前您的框架对事务性消息的支持存在缺陷，主要是DefaultLocalTransactionChecker和DefaultLocalTransactionExecuter的实现存在问题，且不方便扩展。由于各种问题导致事务消息在生产者没有发送commit进行最终确认时触发回查的目的是确保生产者的本地事务正确执行，如果正确则返回commit，如果不正确应该返回Rollback状态并将mq中的事务消息取消掉。而如果按照您目前框架中的处理方式，则无论生产者的本地事务是否成功，都一定会让消息回查成功且让消费者进行消费..... 另外如果采用默认回滚方式虽然能简化实现，但也有些问题，补偿机制完全是额外的工作量，且没有规范化

**Comment by ThierrySquirrel** [comment]
1.Rollback替代为代码块是否能够顺利执行,顺利执行,则提交,否则不开始投递
2.回查触发机制改为,仅在网络,机器出现故障时触发,如果出错,重新发送即可

**Comment by ThierrySquirrel** [comment]
1.框架做到,仅在代码执行一半,出现不可抗力,事务出现失败,如断网,重启,机器损坏
2.您只需要重新投递消息,即可保证最终一致性

**Comment by ThierrySquirrel** [comment]
如果有其它提问,您可以在此次继续留言.
如果没有其它提问,此问题将在24小时内关闭

**Comment by wwjjkk** [comment]
举个例子吧，A银行转账B银行。A本地事务执行失败，但由于网络闪断rollback状态未能发给mq，mq进行定时消息回查，发现A系统正常运行，返回commit将消息提供给B银行系统消费，然后结果就是A银行没有扣款，B银行钱变多了.......  不再讨论啦，希望后续能支持自定义扩展，不然事务消息这块不敢用

**Comment by ThierrySquirrel** [comment]
使用TransactionMessage中的注解transactionStatus即可解决,改为回滚
使用户重试
您在事务上还是过于`贪心`了

**Comment by wwjjkk** [comment]
改为rollback会有另一个问题，如果A本地事务执行成功，但由于网络闪断commit状态未能发给mq，mq进行定时消息回查，发现A系统正常运行，返回rollback取消将消息提供给B银行。那么这时A银行扣款了，B银行的钱没有发生变化。只能进行人工补偿了是吧，人工补偿也得有系统页面或跑批触发吧，这些都是额外的工作量，而且通常不一定能及时处理。其实人工补偿一般是B系统挂掉的时间超过mq存储消息的时间无法保证最终一致性的时候才会进行。生产方一般不需要进行补偿的

**Comment by ThierrySquirrel** [comment]
1.通常情况A事务出错,调用方同时也出错
2.单进行消息补发即可,无需人工

**Comment by ThierrySquirrel** [comment]
如果您想要进一步了解事务,或分布式事务,有兴趣可以了解CAP,Base理论,2CP,3CP等

**Comment by wwjjkk** [comment]
刚举的例子应该比较清晰才对，消息回查时提供默认处理方式是不合适的，因为这时并不确定A系统的本地事务到底有没有执行成功。因此设置成commit或rollback都不合适。单进行消息补发是不适合的

**Comment by wwjjkk** [comment]
base的前提是A的事务执行成功并被mq承认后才能保证最终一致性，不然单纯的补发可能导致最终不一致

**Comment by ThierrySquirrel** [comment]
这好比,用筷子吃饭,为什么不用手抓呢?

**Comment by ThierrySquirrel** [comment]
具体解决方案当然是根据项目来定的.

**Comment by wwjjkk** [comment]
现在聊的是食品安全问题，用筷子吃很方便，希望筷子前端能做成银的，或能够支持用户找来的银外套接到筷子上，做到能验毒就更好啦。目前不是银的，也没法在筷子上外加插件（扩展）来验毒。一般不会吃死人，吃到拉肚子还是有可能的

**Comment by ThierrySquirrel** [comment]
那还是建议您使用原生框架来解决问题呢

**Comment by ThierrySquirrel** [comment]
没有您没有其它问题,将在24小时内关闭此提问.

**Comment by ThierrySquirrel** [comment]
感谢您的提议,在测试版本中,三个默认实现类都可以用户自定义,很快将迎来新的版本.

**Comment by ThierrySquirrel** [comment]
@wwjjkk  2.0.5版本已经发布,ghithub将在明日,进行更新详细操作方式.

**Comment by wwjjkk** [comment]
真效率啊，已下载最新版本并对自定义checker进行了测试，感谢

**Comment by wwjjkk** [comment]
由于自定义事务扩展是全局唯一的，目前想到判断不同业务的方式是在消息中添加指定前缀或额外属性来处理，如果能自定义事务的那几个类，加入到@TransactionMessage里作为属性配置就能灵活了。

**Comment by ThierrySquirrel** [comment]
好的,测试版本已经开发完成,请等待正式版本的发布

**Comment by ThierrySquirrel** [comment]
感谢您的提议,在@CommonMessage与@TransactionMessage中,您可以自由配置三个默认实现类

**Comment by ThierrySquirrel** [comment]
@wwjjkk 2.0.6版本已经发布,ghithub将在今日下午,进行更新详细操作方式.

**Comment by ThierrySquirrel** [comment]
@wwjjkk github已更新,如有需要,您可以随时在此处留言.

**Comment by wwjjkk** [comment]
感谢。另外提一下文档的小bug。订阅消息时方法明明是void但仍然在return....  文档说支持广播，但没有找到广播的例子

**Comment by ThierrySquirrel** [comment]
感谢您的补充,文档已经修复.

**Comment by ThierrySquirrel** [comment]
若无其它提议,将在24小时内关闭此提问.

**Comment by wwjjkk** [comment]
我提了个pull requests，可以参考下，其他没什么了
